title: Uonai
author: Uonai
subtitle: A computer programmer

baseurl: ""

markdown: kramdown

footer_url: "https://github.com/uonai"
footer_text: "GitHub"

profile-picture: images/profile.jpg

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Persona"
   link: "/about"
 - name: "Codex"
   link: "https://github.com/uonai/Codex"
 - name: "GitHub"
   link: "https://github.com/uonai"
